
services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data

  ### Prefect Server API and UI
  server:
    image: prefecthq/prefect:3-python3.12
    restart: always
    volumes:
      - ./flows:/opt/prefect/flows
      - ./utils:/opt/prefect/utils
      - ./logs:/logs
      - ./prefect.yaml:/opt/prefect/prefect.yaml
    command:
      bash -c "
      prefect server start"
    environment:
      - PREFECT_UI_URL=http://127.0.0.1:4200/api
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_LOGGING_LEVEL=INFO
      - PREFECT_LOGGING_HANDLERS_LOG_FILE_FILENAME=/logs/server.log
      # If you want to access Prefect Server UI from anywhere other than the Docker host machine, you will need to change
      # PREFECT_UI_URL and PREFECT_API_URL to match the external hostname/IP of the host machine. For example:
      # - PREFECT_UI_URL=http://external-ip:4200/api
      # - PREFECT_API_URL=http://external-ip:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/prefect

    ports:
      - 4200:4200
    depends_on:
      - database
 

volumes:
  db:
networks:
  default:
    name: prefect-network