services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data

  ### Prefect Server API and UI
  server:
    image: prefecthq/prefect:3-python3.12
    restart: always
    volumes:
      - ./flows:/opt/prefect/flows
      - ./logs:/logs
      - ./prefect.yaml:/opt/prefect/prefect.yaml
      - ./logging.yml:/opt/prefect/logging.yml #aktifin kalau mau ada logfile
    command:
      bash -c "
      prefect server start"
    environment:
      - PREFECT_UI_URL=http://127.0.0.1:4200/api
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_LOGGING_LEVEL=INFO
      - PREFECT_LOGGING_HANDLERS_LOG_FILE_FILENAME=/logs/server.log
      # Enable file logging
      - PREFECT_LOGGING_SETTINGS_PATH=/opt/prefect/logging.yml #aktifin kalau mau ada logfile
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/prefect
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - 4200:4200
    depends_on:
      - database
  
  ### Worker setup with automatic deployment
  worker:
    image: prefecthq/prefect:3-python3.12
    restart: always
    volumes:
      - ./flows:/opt/prefect/flows
      - ./logs:/logs
      - ./prefect.yaml:/opt/prefect/prefect.yaml
      - ./requirements.txt:/opt/prefect/requirements.txt
      - ./startup.sh:/opt/prefect/startup.sh
      - ./logging.yml:/opt/prefect/logging.yml #aktifin kalau mau ada logfile
    command: 
      bash -c "/opt/prefect/startup.sh"
    environment:
      - PREFECT_API_URL=http://server:4200/api
      - PREFECT_LOGGING_LEVEL=INFO
      - PREFECT_LOGGING_HANDLERS_LOG_FILE_FILENAME=/logs/worker.log
      # Enable file logging
      - PREFECT_LOGGING_SETTINGS_PATH=/opt/prefect/logging.yml #aktifin kalau mau ada logfile
    depends_on:
      - server

volumes:
  db:
networks:
  default:
    name: prefect-network