version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(asctime)s %(levelname)s %(name)s %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  flow_runs_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: /logs/flow_runs.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
  
  tasks_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: /logs/tasks.log
    maxBytes: 10485760  # 10MB
    backupCount: 3

  errors_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: standard
    filename: /logs/errors.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
  database:
    class: prefect.logging.handlers.APILogHandler
    level: INFO

loggers:
  prefect:
    level: INFO
    handlers: [console, flow_runs_file,database]
    propagate: false
  
  prefect.flow_runs:
    level: INFO
    handlers: [console, flow_runs_file,database]
    propagate: false
  
  prefect.tasks:
    level: INFO
    handlers: [console, tasks_file,database]
    propagate: false
  
  prefect.extra:
    level: INFO
    handlers: [console]
    propagate: false

root:
  level: INFO
  handlers: [console, errors_file]
  propagate: false